In [1]:
import pandas as pd

In [59]:
import numpy as np
import nltk
import math

In [3]:
from nltk.tokenize import word_tokenize

In [5]:
f=open("D:/Personal and studies/College/Semester 6/Web mining LAB/LAB 1/divy1.txt","r")
a=f.read()
f.close()

f=open("D:/Personal and studies/College/Semester 6/Web mining LAB/LAB 1/divy2.txt","r")
b=f.read()
f.close()

f=open("D:/Personal and studies/College/Semester 6/Web mining LAB/LAB 1/divy3.txt","r")
c=f.read()
f.close()

In [11]:
d=[w.lower() for w in word_tokenize(a)]
e=[w.lower() for w in word_tokenize(b)]
f=[w.lower() for w in word_tokenize(c)]

In [12]:
corpus=[]
corpus.append(a)
corpus.append(b)
corpus.append(c)

In [13]:
corpus

['random things to say about a subject which is awesome and yet full of mysteries',
 "mathematics is a subject which we've studied since the beginning of time and yet it's so full of mystery that we continue to study it without being able to grasp it",
 "the reason for this might be that our brains have not evolved to understand the language of maths, our brains have evolved to roam and hunt and eat. Sitting and working out hypothetical problems in hypothetical planes doesn't help anyone"]

In [32]:
df1=pd.DataFrame([d])
df2=pd.DataFrame([e])
df3=pd.DataFrame([f])

In [62]:
def cal_eucledian(a,b):
    return math.sqrt(sum(np.square(a-b)))

In [63]:
df1=pd.DataFrame([d])
df1

0       1   2    3      4  5        6      7   8        9    10   11  \
0  random  things  to  say  about  a  subject  which  is  awesome  and  yet   

     12  13         14  
0  full  of  mysteries

In [64]:
df4=pd.DataFrame(df1.transpose()[0].value_counts()).transpose()
df4

a  awesome  random  is  mysteries  say  yet  and  subject  things  to  \
0  1        1       1   1          1    1    1    1        1       1   1   

   about  which  of  full  
0      1      1   1     1

In [65]:
df5=pd.DataFrame(df2.transpose()[0].value_counts()).transpose()
df6=pd.DataFrame(df3.transpose()[0].value_counts()).transpose()

In [66]:
df7=pd.concat([df4,df5,df6],sort=False)
df7

a  awesome  random   is  mysteries  say  yet  and  subject  things  ...  \
0  1.0      1.0     1.0  1.0        1.0  1.0  1.0    1      1.0     1.0  ...   
0  1.0      NaN     NaN  1.0        NaN  NaN  1.0    1      1.0     NaN  ...   
0  NaN      NaN     NaN  NaN        NaN  NaN  NaN    3      NaN     NaN  ...   

   roam  for  hunt  language  problems  eat  might  out  help  not  
0   NaN  NaN   NaN       NaN       NaN  NaN    NaN  NaN   NaN  NaN  
0   NaN  NaN   NaN       NaN       NaN  NaN    NaN  NaN   NaN  NaN  
0   1.0  1.0   1.0       1.0       1.0  1.0    1.0  1.0   1.0  1.0  

[3 rows x 63 columns]

In [67]:
x=[]
for i in range(3):
    x.append(np.nan_to_num(df7.values[i]))
x[0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
cal_eucledian(x[0],x[1])

6.164414002968976

In [70]:
cal_eucledian(x[1],x[2])

9.16515138991168

In [71]:
cal_eucledian(x[0],x[2])

8.12403840463596

In [73]:
print("Document 0 and 1 have least distance")

Document 0 and 1 have least distance


In [46]:
np.nan_to_num(df7.values[0])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

In [43]:
vectorizer=CountVectorizer()

In [44]:
vectorizer.fit(corpus)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [55]:
vector_a=vectorizer.transform([a])
vector_b=vectorizer.transform([b])
vector_c=vectorizer.transform([c])

In [56]:
x=vector_a.toarray()
y=vector_b.toarray()
z=vector_c.toarray()

In [57]:
x

array([[0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1]], dtype=int64)

In [54]:
print(vectorizer.vocabulary_)

{'random': 35, 'things': 47, 'to': 50, 'say': 38, 'about': 1, 'subject': 44, 'which': 54, 'is': 21, 'awesome': 4, 'and': 2, 'yet': 57, 'full': 14, 'of': 30, 'mysteries': 27, 'mathematics': 24, 'we': 53, 've': 52, 'studied': 42, 'since': 39, 'the': 46, 'beginning': 6, 'time': 49, 'it': 22, 'so': 41, 'mystery': 28, 'that': 45, 'continue': 9, 'study': 43, 'without': 55, 'being': 7, 'able': 0, 'grasp': 15, 'reason': 36, 'for': 13, 'this': 48, 'might': 26, 'be': 5, 'our': 31, 'brains': 8, 'have': 16, 'not': 29, 'evolved': 12, 'understand': 51, 'language': 23, 'maths': 25, 'roam': 37, 'hunt': 18, 'eat': 11, 'sitting': 40, 'working': 56, 'out': 32, 'hypothetical': 19, 'problems': 34, 'in': 20, 'planes': 33, 'doesn': 10, 'help': 17, 'anyone': 3}


In [62]:
x-z

array([[ 0,  1, -2, -1,  1, -1,  0,  0, -2,  0, -1, -1, -2, -1,  1,  0,
        -2, -1, -1, -2, -1,  1,  0, -1,  0, -1, -1,  1,  0, -1,  0, -2,
        -1, -1, -1,  1, -1, -1,  1,  0, -1,  0,  0,  0,  1, -1, -2,  1,
        -1,  0, -1, -1,  0,  0,  1,  0, -1,  1]], dtype=int64)

In [60]:
np.linalg.norm(x-y)

6.082762530298219