In [1]:
import pandas as pd

In [2]:
import numpy as np
import nltk
import math

In [3]:
from nltk.tokenize import word_tokenize

In [4]:
f=open("D:/Personal and studies/College/Semester 6/Web mining LAB/LAB 1/divy1.txt","r")
a=f.read()

f=open("D:/Personal and studies/College/Semester 6/Web mining LAB/LAB 1/divy2.txt","r")
b=f.read()

f=open("D:/Personal and studies/College/Semester 6/Web mining LAB/LAB 1/divy3.txt","r")
c=f.read()
f.close()

In [5]:
d=[w.lower() for w in word_tokenize(a)]
e=[w.lower() for w in word_tokenize(b)]
f=[w.lower() for w in word_tokenize(c)]

In [6]:
df1=pd.DataFrame([d])
df2=pd.DataFrame([e])
df3=pd.DataFrame([f])

In [7]:
df1=pd.DataFrame([d])
df1

0       1   2    3      4  5        6      7   8        9    10   11  \
0  random  things  to  say  about  a  subject  which  is  awesome  and  yet   

     12  13         14  
0  full  of  mysteries

In [8]:
df4=pd.DataFrame(df1.transpose()[0].value_counts()).transpose()
df4

and  about  awesome  full  say  random  a  yet  of  things  mysteries  \
0    1      1        1     1    1       1  1    1   1       1          1   

   subject  is  which  to  
0        1   1      1   1

In [9]:
df5=pd.DataFrame(df2.transpose()[0].value_counts()).transpose()
df6=pd.DataFrame(df3.transpose()[0].value_counts()).transpose()

In [10]:
df7=pd.concat([df4,df5,df6],sort=False)
df7

and  about  awesome  full  say  random    a  yet  of  things  ...  n't  \
0    1    1.0      1.0   1.0  1.0     1.0  1.0  1.0   1     1.0  ...  NaN   
0    1    NaN      NaN   1.0  NaN     NaN  1.0  1.0   2     NaN  ...  NaN   
0    3    NaN      NaN   NaN  NaN     NaN  NaN  NaN   1     NaN  ...  1.0   

   maths  language  might  does  problems  eat  sitting    .  anyone  
0    NaN       NaN    NaN   NaN       NaN  NaN      NaN  NaN     NaN  
0    NaN       NaN    NaN   NaN       NaN  NaN      NaN  NaN     NaN  
0    1.0       1.0    1.0   1.0       1.0  1.0      1.0  1.0     1.0  

[3 rows x 63 columns]

In [11]:
x=[]
for i in range(3):
    x.append(np.nan_to_num(df7.values[i]))
x[0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
def cal_eucledian(a,b):
    return math.sqrt(sum(np.square(a-b)))

In [13]:
cal_eucledian(x[0],x[1])

6.164414002968976

In [14]:
cal_eucledian(x[1],x[2])

9.16515138991168

In [15]:
cal_eucledian(x[0],x[2])

8.12403840463596

In [16]:
print("Document 0 and 1 have least distance")

Document 0 and 1 have least distance


In [18]:
corpus=[]
corpus.append(a)
corpus.append(b)
corpus.append(c)

In [19]:
corpus

['random things to say about a subject which is awesome and yet full of mysteries',
 "mathematics is a subject which we've studied since the beginning of time and yet it's so full of mystery that we continue to study it without being able to grasp it",
 "the reason for this might be that our brains have not evolved to understand the language of maths, our brains have evolved to roam and hunt and eat. Sitting and working out hypothetical problems in hypothetical planes doesn't help anyone"]

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
vectorizer=CountVectorizer()

In [22]:
vectorizer.fit(corpus)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [23]:
vector_a=vectorizer.transform([a])
vector_b=vectorizer.transform([b])
vector_c=vectorizer.transform([c])

In [24]:
x=vector_a.toarray()
y=vector_b.toarray()
z=vector_c.toarray()

In [25]:
x

array([[0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1]], dtype=int64)

In [26]:
print(vectorizer.vocabulary_)

{'random': 35, 'things': 47, 'to': 50, 'say': 38, 'about': 1, 'subject': 44, 'which': 54, 'is': 21, 'awesome': 4, 'and': 2, 'yet': 57, 'full': 14, 'of': 30, 'mysteries': 27, 'mathematics': 24, 'we': 53, 've': 52, 'studied': 42, 'since': 39, 'the': 46, 'beginning': 6, 'time': 49, 'it': 22, 'so': 41, 'mystery': 28, 'that': 45, 'continue': 9, 'study': 43, 'without': 55, 'being': 7, 'able': 0, 'grasp': 15, 'reason': 36, 'for': 13, 'this': 48, 'might': 26, 'be': 5, 'our': 31, 'brains': 8, 'have': 16, 'not': 29, 'evolved': 12, 'understand': 51, 'language': 23, 'maths': 25, 'roam': 37, 'hunt': 18, 'eat': 11, 'sitting': 40, 'working': 56, 'out': 32, 'hypothetical': 19, 'problems': 34, 'in': 20, 'planes': 33, 'doesn': 10, 'help': 17, 'anyone': 3}


In [27]:
x-z

array([[ 0,  1, -2, -1,  1, -1,  0,  0, -2,  0, -1, -1, -2, -1,  1,  0,
        -2, -1, -1, -2, -1,  1,  0, -1,  0, -1, -1,  1,  0, -1,  0, -2,
        -1, -1, -1,  1, -1, -1,  1,  0, -1,  0,  0,  0,  1, -1, -2,  1,
        -1,  0, -1, -1,  0,  0,  1,  0, -1,  1]], dtype=int64)

In [28]:
np.linalg.norm(x-y)

6.082762530298219

In [29]:
np.linalg.norm(y-z)

8.888194417315589

In [30]:
np.linalg.norm(x-z)

7.874007874011811

In [31]:
print("Document 0 and 1 have least distance")

Document 0 and 1 have least distance
